# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

commands:
  test:
    description: Run local test cases
    steps:
      - run: yarn test

jobs: 
  build: 
    docker:       
      - image: circleci/node:12
    steps:       
      - test
